### ISSUE TITLE
About this bundle

### ISSUE THREAD

**Issue by Maxwell2022** [amigos-del-rigor/ADRCassandraBundle#1]
Just like to know if this bundle is production friendly? I cannot see any release and the last commit is 4 months old.

Cheers, Maxime

**Comment by ricardclau** [comment]
I just saw that issue, I don't know why Github did not notify me, so sorry about this massive delay @Maxwell2022 !

The bundle is just some abstraction over the phpcassa classes and adding the calls to the profiler whenever you execute Symfony in dev mode. I have tested it in some small projects as an experiment but AFAIK there is nobody actually using it in production, let's say with heavy load

I actually stopped the work on it, since I did not see much interest, however if that is the case we can work together to add more tests, functionality that you think would be useful and make a decently stable version

Thoughts? Sorry again about the big delay
